# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: PantoYT.termwall
PackageVersion: 1.1.0
InstallerType: inno
Scope: user
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PantoYT/termwall/releases/download/v1.1.0/termwall-setup-1.1.0.exe
  InstallerSha256: B057B55B5FD023859C1F5895FA6C4EB2A0A66351B6D388DA94517951DED6BA04
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-04
